### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by as996656503** [ShikyoKira/Project-New-Reign---Nemesis-Main#286] opened 2020-06-02 16:53 UTC
![Desktop Screenshot 2020 06 03 - 00 46 17 36](https://user-images.githubusercontent.com/20008235/83547364-b0202300-a534-11ea-9807-93986fc305d5.png)

**Comment by ShikyoKira** [comment] 2020-06-02 20:20
This issue is not in accordance to the criteria stated in the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repo. This issue will be closed of no update to this to meet its criteria in 5 days

**Comment by as996656503** [comment] 2020-06-03 03:14
> 此问题与该存储库[主页](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main)中所述的标准不符。此问题将在5天之内完成更新，以满足其标准
Thank you for your work！

**Comment by as996656503** [comment] 2020-06-03 03:14
> 此问题与该存储库[主页](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main)中所述的标准不符。此问题将在5天之内完成更新，以满足其标准

Thanks for your work！

**Comment by ShikyoKira** [comment] 2020-06-03 10:57
正確的翻譯 :
此问题与该存储库主页中所述的标准不符。若此问题在5天內沒更新以滿足标准，此问题將被關閉

**Comment by ShikyoKira** [comment] 2020-06-06 04:28
Closed. Reason being
- a duplicate of #273 
- author of this issue seem to no longer to want to engage in this issue

**Closed by ShikyoKira** 2020-06-06 04:28 UTC
