### ISSUE TITLE
Animations aren't playing for humanoids.

### ISSUE THREAD

**Issue by flipdark95** [ShikyoKira/Project-New-Reign---Nemesis-Main#142] opened 2020-02-05 08:30 UTC
Hey there, I've had a issue for a while now where my character doesn't seem to have any animations at all. They stay in the idle pose and slide around when moving, and jumping doesn't do anything, and neither does equipping weapons. 

I have Nemesis installed through Mod Organizer 2 like the rest of my mods, and as far as I can tell, it's detected XPMSE and all the other LL mods I have for my darker playthroughs. 

I've tried looking through the virtual files to see if the skeletons installed by XPMSE are being overridden, but they're not, and my load order seems to just be fine. XPMSE.esp is at the bottom of the load order, and Nemesis is just above it.

Am I missing something? There isn't really any mention about what animations mods can be used through Nemesis either.

Anyway, thanks for responding to my issue if you do. Otherwise I might need to go back to FNIS SE, and it really is too slow these days.

**Comment by ShikyoKira** [comment] 2020-02-05 19:36
Hi, i have noted this issue as well. Report by my testers. I have successfully recreated this issue. A temporary fix would be to reduce the animation count, meanwhile I'll actively fixing this problem

**Comment by flipdark95** [comment] 2020-02-06 04:54
Gotcha, that's what I've done in the meantime as well. I've gotten contradictory animation counts from FNIS SE and from Nemesis, so I think the best case is to just reduce the amount of animations I have installed. Thanks for replying :)

**Comment by ShikyoKira** [comment] 2020-02-08 08:28
FNIS SE animation count method is different from Nemesis. So thats something to be noted as well. FNIS counts female and male animation as 1 animation, Nemesis counts it as 2 because they are 2 different projects (i think this is the best i can come up with)

**Comment by royale011** [comment] 2020-04-05 10:30
Hi!

Same problem here. I just wonder when the fix will be done, and I really want to enjoy some mods excluded to Nemesis like CGO+.

I've checked the warning message and shows tons of "Animation has not been registered" warnings for SSE default animations (which are not been modded), like attacking, walking, sprinting and so on.

Anyway thanks ShikyoKira and wish the fixes (or new version) will be done soon!

**Comment by ShikyoKira** [comment] 2020-05-27 05:56
Duplicate of #178 
fixed in v0.84 onwards

**Closed by ShikyoKira** 2020-05-27 05:56 UTC
