### ISSUE TITLE
Engine Update takes nearly half an hour

### ISSUE THREAD

**Issue by erri120** [ShikyoKira/Project-New-Reign---Nemesis-Main#131] opened 2020-01-17 16:41 UTC
![17-01-2020 17-33-53 Nemesis_Unlimited_Behavior_Engine](https://user-images.githubusercontent.com/16577545/72629135-9bf1d580-3947-11ea-8912-eb466d78ff32.png)
1626 secs aka 27.1 mins
In comparision with the actual behavior generation:
`Behavior generation complete: 66 second(s) taken`

My System:
i7-7700k 4@4.2Ghz
16GB DDR4-3200
GTX 1060 6GB

running on an SSD with the latest Win 10 (Enterprise Edition)

**Comment by ShikyoKira** [comment] 2020-01-18 04:36
Apparently this issue is quite random to me that I can't recreate it all the time but i'll still try to look into it. Thanks for reporting

**Comment by maboroshinokiseki** [comment] 2020-01-21 14:47
Try switch to another window, it works for me.

**Comment by ShikyoKira** [comment] 2020-05-27 05:57
Duplicate of #240 
fixed in v0.84 onwards

**Closed by ShikyoKira** 2020-05-27 05:57 UTC
