### ISSUE TITLE
Error 6001 when i update engine

### ISSUE THREAD

**Issue by pooh215** [ShikyoKira/Project-New-Reign---Nemesis-Main#341] opened 2020-08-01 07:38 UTC
version is 0.84 sse

But it is no problem in 0.83c
----------------------------------------------------------------------------------------------------------------
Initializing engine update

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: �b�h�줸�ժ��ت��r�X�����A�S���o�� Unicode �r���i�H�����쪺�r���C

Failed to update engine

**Comment by ShikyoKira** [comment] 2020-08-01 08:07
All unicode issue is being directed to same issue

Duplicate of #273

**Closed by ShikyoKira** 2020-08-01 08:07 UTC

**Comment by pooh215** [comment] 2020-08-01 08:48
> All unicode issue is being directed to same issue
> 
> Duplicate of #273

i find the solution 
use Locale Emulator to open nemesis and set the language to english
it can update engine now and solve unicode problem
