### ISSUE TITLE
Error 1207 failed to output xml

### ISSUE THREAD

**Issue by willhedi** [ShikyoKira/Project-New-Reign---Nemesis-Main#179] opened 2020-03-24 04:06 UTC
ERROR(1207): Failed to output xml file. Please ensure that the hkx file is readable and valid by contacting the mod author.
Here the Patchlog
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4373083/PatchLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4373085/UpdateLog.txt)

**Comment by ShikyoKira** [comment] 2020-03-26 11:19
I suspect said file is in 64bit, which isn't compatible with your skyrim version. Please double check that file

**Comment by willhedi** [comment] 2020-03-28 04:43
which file i must check you know im little bit confused

**Comment by ShikyoKira** [comment] 2020-03-31 16:24
`d:\game\the elder scrolls v skyrim - legendary edition\data\meshes\actors\character\Character Assets Female\skeleton_female.hkx`

**Comment by ShikyoKira** [comment] 2020-04-21 14:39
Duplicate of #173

**Closed by ShikyoKira** 2020-04-21 14:39 UTC
