### ISSUE TITLE
Lot of Warning count:No animation except T-posing

### ISSUE THREAD

**Issue by whitewolf2899** [ShikyoKira/Project-New-Reign---Nemesis-Main#220] opened 2020-04-20 12:30 UTC
I installed the TK Dodge with Nemesis a number of times but no animations.does nemesis scan the hardware or the data files like FNIS??.

**Comment by whitewolf2899** [comment] 2020-04-20 12:31
Except many warnings are shown in that place that alternate animation not available.

**Comment by ShikyoKira** [comment] 2020-04-20 15:13
then these warnings are unrelated to your issue

DId you tick Ultimate Combat/TK Dodge in the mod list when running Nemesis?

**Comment by whitewolf2899** [comment] 2020-04-20 15:20
Btw thank you for your response.Yup did that still tried many times I installed it manually by extracting all the nemesis files on to data folder. Still the engine is showing warnings related to "no alternate animations found". All humanoids have no animation at all except creatures.

**Comment by whitewolf2899** [comment] 2020-04-21 06:01
Am closing this issue because another user is also facing the same problem

**Comment by ShikyoKira** [comment] 2020-05-26 19:03
Possible duplicate of #178

**Closed** 2020-05-26 20:46 UTC
