### ISSUE TITLE
Nemesis not working properly with dodge mods (TUDM, TK DODGE, CGO's dodge)

### ISSUE THREAD

**Issue by xFrosty7** [ShikyoKira/Project-New-Reign---Nemesis-Main#177] opened 2020-03-22 12:36 UTC
when using any of the dodge mods mentioned above with nemesis, the character (npcs aswell) keeps rolling in his place whenever i try to dodge, but only in 3rd person, in 1st person it works fine.
fnis and it's mods are already deleted, i tried disabling all my mods excluding one of the dodge mods and Nemesis, emptying overwrite folder (mo2), running nemesis generator with it's patch, still not working.
i reckon it's a bug from nemesis since they work fine without it, could you please fix this?

**Comment by ShikyoKira** [comment] 2020-03-22 18:15
Duplicate of #157

**Closed by ShikyoKira** 2020-03-22 18:15 UTC
