### ISSUE TITLE
Error 6002: An exception has occured while patching

### ISSUE THREAD

**Issue by jeffreySJ** [ShikyoKira/Project-New-Reign---Nemesis-Main#212] opened 2020-04-15 05:47 UTC
I get this error when I click "Launch Nemesis Behavior Engine". The catch is it only happens when I _also_ have Nemesis PCEA setup. When I disable Nemesis PCEA... the engine runs fine.

Here's the output

````
Checking engine version
Engine is up to date
Version Code: 6657-8152

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: agpo
Mod Checked 3: dscgo
Mod Checked 4: dsmove
Mod Checked 5: rthf

Mod installed: XPMSE
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: None
Message: boost::filesystem::copy_file

Failed to generate behavior
````

**Comment by ShikyoKira** [comment] 2020-04-15 07:15
Duplicate of #195

**Closed by ShikyoKira** 2020-04-15 07:15 UTC
