### ISSUE TITLE
CTD on startup

### ISSUE THREAD

**Issue by Assad76** [ShikyoKira/Project-New-Reign---Nemesis-Main#207] opened 2020-04-14 03:17 UTC
Hi. I did everything according to this YT tutorial (https://www.youtube.com/watch?v=4lSp3tZI2xc&t=247s)
I start the game and it crashes right before the menus appear(by menues I mean the ones that you can select load or new game). I have lots of animation mods. I also have deleted many animations just because I didn't like them. Fnis did give me a warning about them but it was running fine. 
I attached the logs:

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4472924/PatchLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4472925/UpdateLog.txt)
[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4472926/CriticalLog.txt)

**Comment by ShikyoKira** [comment] 2020-04-14 05:26
Try reduce the number of animations to around 10k. This isn't nemesis limitation, its just a bug. Will be fixed in upcoming version

**Comment by ShikyoKira** [comment] 2020-04-14 05:27
Duplicate of #135

**Closed by ShikyoKira** 2020-04-14 05:27 UTC

**Comment by Assad76** [comment] 2020-04-14 18:47
I did what you asked but now my character's leg are not moving. Only the upper body is leaning and moving,
I can move around but my legs are stationary. 
it's the same for npcs.
