### ISSUE TITLE
WARNING(1013) & no one attack animation not working

### ISSUE THREAD

**Issue by KYLHACKER** [ShikyoKira/Project-New-Reign---Nemesis-Main#196] opened 2020-04-10 10:40 UTC
WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_runright.hkx

WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_runstrafeleft.hkx

WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_runstraferight.hkx

WARNING(1013): Animation has not been registered in defaultfemale.hkx file. The animation will not work. Please contact the mod author
Animation: animations\2hm_walkbackward.hkx

I have warning 1013 in all attack and walk animation, and only idle animation work properly. Also trying to attack mudcrab, and he didn't use animations.

**Comment by ShikyoKira** [comment] 2020-04-11 19:36
Reinstall nemesis. Warning is a sign that the problem is very likely to be on your side

**Comment by ShikyoKira** [comment] 2020-05-26 19:00
Duplicate of #180

**Closed by ShikyoKira** 2020-05-26 19:00 UTC
