### ISSUE TITLE
MO2 not running Nemesis on launch

### ISSUE THREAD

**Issue by Jumu3668** [ShikyoKira/Project-New-Reign---Nemesis-Main#234] opened 2020-04-29 10:54 UTC
This one is also different than the other issue someone had since theirs runs in the background and it seemed to be an issue with Qt5, but for me, the program doesn't even run at all. The symptoms are almost identical to this one that was posted a couple years ago
https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/issues/84
Unfortunately the convo was moved to discord, so they never posted the solution.

Here's also a video demonstrating the problem. 
https://www.youtube.com/watch?v=_1QZk46VED4

**Comment by cuzfinal** [comment] 2020-04-30 03:04
+1, same situation

**Comment by ShikyoKira** [comment] 2020-04-30 17:03
#84 that seems to be a crash not that it doesn't run. Since you mention Qt5, i'll close this as it is very likely to be a duplicate of #211 . Move our future discussion there unless there is any new findings suggesting that it is a different issue

**Closed by ShikyoKira** 2020-04-30 17:03 UTC

**Comment by Jumu3668** [comment] 2020-05-01 06:31
OK I just got back from updating windows 10. I upgraded from Windows 10 1809 to 1909 and updated it to KB4550945 (April 21st Release) and it is still  doing the exact same thing
