### ISSUE TITLE
Halo Poser

### ISSUE THREAD

**Issue by Keitsoru** [ShikyoKira/Project-New-Reign---Nemesis-Main#266] opened 2020-05-25 21:57 UTC
Hey, Shikyo, I know you feel as though the issue was resolved, but even if a user disables every animation mod but Halo's and SOMEHOW gets the game to start, the issue still remains that there is no walking animation. I have tested with and without CGO, and it seems to be a persistent issue. If you could PLEASE look further in to this, it would be appreciated.

**Comment by ShikyoKira** [comment] 2020-05-26 11:43
Duplicate of #178 
It has been addressed. Thanks

**Closed by ShikyoKira** 2020-05-26 11:43 UTC

**Comment by Keitsoru** [comment] 2020-05-31 05:04
I don't understand. What am I supposed to do to fix the issue, then?

Everything I can find addresses the CTD, not the sliding issue.

**Comment by Keitsoru** [comment] 2020-05-31 06:09
Okay, after rereading a bit, I found where you set to take the dev build behavior templates and put them in Nemesis's folder. Works like a charm.
