### ISSUE TITLE
Error 1056

### ISSUE THREAD

**Issue by iamkarmic** [ShikyoKira/Project-New-Reign---Nemesis-Main#228] opened 2020-04-23 18:38 UTC
Every time I attempt to launch the engine I would end up with this message.

ERROR(1056): Invalid element. Only "F" "L", or digit is acceptable as input element. Please contact the template creator | Template: b | File: #0110 | Line: 23 | Option: b[][B]

Failed to generate behavior.

Any idea what the problem is here?

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4524544/PatchLog.txt)

**Comment by ShikyoKira** [comment] 2020-04-24 05:36
Try reinstall these mods.
- Animated Eating Redux
- DarkSouls combat
- Critical Hit
- Immersive Animated Looting
- Potion Animated Fix
- XPMSE

**Comment by ShikyoKira** [comment] 2020-04-24 05:45
Duplicate of #170

**Closed by ShikyoKira** 2020-04-24 05:45 UTC
