### ISSUE TITLE
Character stuck in T pose during ragdoll

### ISSUE THREAD

**Issue by HomeGrownTeddybear** [ShikyoKira/Project-New-Reign---Nemesis-Main#394] opened 2020-09-27 22:18 UTC
When I get knocked down my character stays in T pose on the floor and I get CTD after 3-5 seconds. 
Mods that I use are Animal Tweaks, Wildcat and Combat gameplay overhaul.

**Comment by ShikiRyugi** [comment] 2020-10-03 22:54
Hmm, that a highly unusual problem. Normally any of the mods should be fine and according to my knowledge at least Wildcat and CGO should work together just fine (I don't know Animal Tweaks, but form the description page it should also work just fine).  

1) Are Animal Tweaks, Wildcat and CGO really the only mods you have installed? Especially, are you using any animation mods?
2) Try running Nemesis again.
3) Did you install Wildcat before CGO and had CGOs files take priority / overwrite in case of any conflicts?
4) Try a new game with only one of a.m. mods and try if the problem still exists. If not, try again after adding one more mod... This way we can get a closer idea which mod or mod combination is the problem. 
( 5) I'm not sure if this'll make any difference, but you could also try downloading an older version of Nemesis and try your save game again. It actually should not make any difference, but this checks / ensures that its not a problem caused by any changes in the latest Nemesis version.)

**Comment by HomeGrownTeddybear** [comment] 2020-10-04 02:28
Well those two mods adds the ability for the player to fall down in ragdoll.
Wildcat - if you sprint with a specific wound character.
Animal tweaks - gives bears, troll, sabre cat ability to knockdown the player.
I don't have any other mods that adds this feature, the animation for ragdoll is from base game and only xmpse changes the force of it.

**Comment by ShikyoKira** [comment] 2020-10-10 20:39
Any update?

**Comment by HomeGrownTeddybear** [comment] 2020-10-11 22:22
Haven't played any Skyrim recently I started modding SE a week ago, got pretty much the same mods and custom animations but I tested out ragdoll and couldn't replicate the bug. Maybe it was the 32 bit version on its knees.

**Comment by ShikyoKira** [comment] 2020-10-12 12:02
Well, skyrim works in mysterious way anyway. If it is no longer an issue, you can close this issue now. Thanks for the update

**Closed** 2020-10-13 01:14 UTC
