### ISSUE TITLE
I can't update Engine

### ISSUE THREAD

**Issue by ng2742** [ShikyoKira/Project-New-Reign---Nemesis-Main#164] opened 2020-03-11 06:10 UTC
I apologize for using a translator because I am not good at English.

I installed nemesis, but the engine update is not working.
The program turns off at about 60% of the update process after showing exactly the high cpu utilization rate.

I am a le user and I am using mo, My cpu is i7-8700.
The namesis installed in the data folder, and nemesis version is 0.83c.
And no message or log appears when the program is turned off.

What's even more strange is that se nemesis works normally.

**Comment by ShikyoKira** [comment] 2020-03-11 16:40
maybe your pc killed the program due to high cpu utilization. This is just a speculation. But so far i have received several reports lag and stuck due to high cpu utilization. I'll tone down the utilization in next update. And hopefully that will fix your problem. Thanks for reporting

**Comment by DarthZenn** [comment] 2020-03-12 12:13
I have the same problem when updating the engine. It crash at 70% - 79%-ish. But I just found out that  my nemesis engine got overwrited by some files in the Overwrite tab at the bottom of the left panel .So I move all of the files in the overwrite folder in mod organizer folder to another folder. And BOOM! Works flawlessly. Hope this work for u too.

**Comment by ng2742** [comment] 2020-03-12 14:36
> 엔진을 업데이트 할 때도 같은 문제가 있습니다. 70 %-79 % -ish에서 충돌합니다. 그러나 방금 왼쪽 패널 하단의 덮어 쓰기 탭에서 일부 파일이 내 Nemesis 엔진을 덮어 썼다는 것을 알았습니다. 따라서 mod Organizer 폴더의 덮어 쓰기 폴더의 모든 파일을 다른 폴더로 옮깁니다. 그리고 붐! 완벽하게 작동합니다. 이 작품도 당신을 위해 희망하십시오.

nope, that's not my case.

**Comment by ShikyoKira** [comment] 2020-04-15 07:31
Duplicate of #198

**Closed by ShikyoKira** 2020-04-15 07:31 UTC
