### ISSUE TITLE
error 1052

### ISSUE THREAD

**Issue by HooDee101** [ShikyoKira/Project-New-Reign---Nemesis-Main#232] opened 2020-04-27 08:17 UTC
ERROR(1052): Invalid element. Only empty, "F", "L" or digit is acceptable as input element. Please contact the template creator
Template: s
File: #0200
Line: 23
Option: 					<hkparam name="eventId">$eventID[s[F][main_anim_event]]$</hkparam>

Failed to generate behavior

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4538317/PatchLog.txt)

any solution??

**Comment by ShikyoKira** [comment] 2020-04-27 19:16
Will be fixed in next update. It can be fixed by reinstalling certain animation mods, i can't pinpoint which. I also see that you have a lot of animations installed. I would recommend either not use current version of Nemesis or remove some of the mods keep them below 13k

Duplicate of #170 despite different error code

**Closed by ShikyoKira** 2020-04-27 19:16 UTC

**Comment by HooDee101** [comment] 2020-04-28 03:50
> Will be fixed in next update. It can be fixed by reinstalling certain animation mods, i can't pinpoint which. I also see that you have a lot of animations installed. I would recommend either not use current version of Nemesis or remove some of the mods keep them below 13k
> 
> Duplicate of #170 despite different error code

Thank you!!
