### ISSUE TITLE
Error 1166 / # 609-9900

### ISSUE THREAD

**Issue by evittalex** [ShikyoKira/Project-New-Reign---Nemesis-Main#283] opened 2020-06-01 13:05 UTC
Hopefully the image copes through.

Error 11 66, fDualWieldSpeedMult, when utilizing AGO, CGO, 360 Movement behavior on SSE. 

![image](https://user-images.githubusercontent.com/66256254/83411752-db94f780-a3e6-11ea-9d9a-c9ae0331b7c0.png)

**Comment by ShikyoKira** [comment] 2020-06-01 17:21
removing which mod fixes it?

**Comment by evittalex** [comment] 2020-06-01 18:18
CGO 1.0.0 was installed at that point and was causing the error and a CTD upon save load/new game. Upgrading to 1.10 removed the (1166) error message but still caused CTD upon save load/new game. 
Tried to manually remove FNIS installation in both cases to get around this, no dice, only upon de-activation of CGO would it work. 

Couldn't find clear documentation about this particular interaction; i understand that FNIS should not be installed alongside 1.01 or 1.10 as per the author but tested it just to try to troubleshoot further and collect more info.

**Comment by ShikyoKira** [comment] 2020-06-01 18:22
does having Nemesis but CGO unchecked in Nemesis stop the CTD?

**Comment by evittalex** [comment] 2020-06-01 18:23
Confirmed that is the case.

**Comment by ShikyoKira** [comment] 2020-06-01 19:06
inform DServant then. I holds no responsible any issues caused by patches distributed by mod authors that uses my framework. And since you are the only person having this issue. I suggest you clear up your mod list and do more extensive testing before you bother him about this. I'll close this issue now. Thanks for the update

**Closed by ShikyoKira** 2020-06-01 19:06 UTC
