### ISSUE TITLE
Skyrim SE CTD when using Nemesis and ~15K animations

### ISSUE THREAD

**Issue by badbonez** [ShikyoKira/Project-New-Reign---Nemesis-Main#199] opened 2020-04-11 17:00 UTC
I am getting a CTD whenever I generate over ~15k animations using Nemesis.  (I say around 15k because I am not sure of the exact number.)  And it does not seem to matter which animation packs I use, all that matters is that I go over ~15k.  For instance, in patchlog 15k.txt I have over 15K animations registered, and when I run Skyrim, the game will CTD before getting to the loading screen.  If I run Nemesis with less than 15K, (see patchlog.txt) the game runs normally.  And I am using the [Animation Limit Crash Fix SSE](https://www.nexusmods.com/skyrimspecialedition/mods/31146)

 I've tried these same animations with FNIS and I do not get a CTD, no matter how many mods I add.

EDIT:  I have also added more animation mods, not run NEMESIS and the game will load as expected.  It's only when I generate animations with Nemesis that this occurs.

Any advice?  Thank you.
[PatchLog 15k.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4464994/PatchLog.15k.txt)
[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4464997/PatchLog.txt)
[animationsetdatasinglefile.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4464999/animationsetdatasinglefile.txt)
[animationdatasinglefile.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4465000/animationdatasinglefile.txt)

**Comment by ShikyoKira** [comment] 2020-04-11 19:41
Animation Limit Crash Fix only helps increasing the number of allowable ClipGenerator. What i have found out during my research in there is another limitation that Animation Limit Crash Fix does not fix that is on the AnimData side. if AnimData goes above 32767, it will still crash

Anyway, this is a duplicate of #178

**Closed by ShikyoKira** 2020-04-11 19:41 UTC

**Comment by badbonez** [comment] 2020-04-11 20:52
So how do I fix this?

**Comment by MrAlgur** [comment] 2024-06-08 12:30
hello  @badbonez i have the same error but with a max of 13k animation if i have more i get a ctd. Did u solve it personnaly idk how to resolve it .

**Comment by Zag2005** [comment] 2024-07-14 15:45
Did face the same so switched to pandora but again faced the exact ctd after 23k animation .You can easily fix that by opening OAR /DAR menu (default keys are SHIFT + I ) then go to settings at the bottom and again tick Increase the animation limit at the bottom . Hope this fixes :))

https://www.youtube.com/watch?v=KXoLhqSz7eQ  (Thanks to him )

**Comment by MrAlgur** [comment] 2024-07-15 17:40
Thx it works the only change i made is for Enginefixe i had 2500 on the line MaxStdio i increase to 16384. 

👌thanks
