### ISSUE TITLE
Error 6002 or Crash when Launching Nemesis

### ISSUE THREAD

**Issue by GitRealGud** [ShikyoKira/Project-New-Reign---Nemesis-Main#219] opened 2020-04-19 23:43 UTC
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: None
Message: boost::filesystem::remove: Access is denied: "temp_behaviors\xml\0_master.xml"

Error 6002 Keeps Happening when using MO when launching Nemesis and sometimes Nemesis automatically crashes by closing itself after displaying the error. It doesn't seem to be involved with admin or antivirus issues since I disabled my antiviruses and gave admin access to both MO and Nemesis to no avail. Also re installation of latest Nemesis still reproduces the same error.  Updating Nemesis works fine however and causes no errors or crashes.

**Comment by ShikyoKira** [comment] 2020-04-20 15:11
Duplicate of #195

**Closed by ShikyoKira** 2020-04-20 15:11 UTC
