### ISSUE TITLE
Enemies don't hit me

### ISSUE THREAD

**Issue by HaloGalaxy25** [ShikyoKira/Project-New-Reign---Nemesis-Main#238] opened 2020-05-01 16:16 UTC
Im not sure if this is a problem with nemesis but, this all started after I installed Nemesis and CGO, i've already issued this problem on the CGO nexus mod page but the author hasn't answered me back yet, anyways enemies don't appear to be hitting me with any close range weapons, they just stand their with sword in hand staring at me, or they just repeatedly shield bash me, they do use spells and long range weapons, but never swords or any blunt weapons, it appears to only affect humans not creatures. NPCs don't hit each other either. At first I thought it was a problem with the mod Critical hit since that mod only works on humans, but even after uninstalling it, it still doesn't work, I've also uninstall other combat mods besides CGO, i've even started a new game but the problem still persists. As I typed this I realized that other has the same problem but I still don't understand how to fix it so i'm just gonna leave this here just in case

**Comment by ShikyoKira** [comment] 2020-05-02 06:57
after uninstalling them, did you run nemesis and re-patch everything?

**Comment by HaloGalaxy25** [comment] 2020-05-02 07:14
Yes

**Comment by ShikyoKira** [comment] 2020-05-13 05:21
Duplicate of #180 
Looking into it. Thanks for reporting

**Closed** 2020-05-13 05:22 UTC
