### ISSUE TITLE
"Update Engine" can make CPU hit 100% utilization.

### ISSUE THREAD

**Issue by tridbee** [ShikyoKira/Project-New-Reign---Nemesis-Main#188] opened 2020-03-31 15:42 UTC
Hi Shikyo, I've been using FNIS for quite some time and came across your Combat Gameplay Overhaul mod, which requires Nemesis. I've made my switch to Nemsis but I encountered 2 issues:

- When updating engine through Nemesis, my Ryzen 5 3600X hits 100% immediately and stay so for about 2 minutes or more which really heat up the system and slow down the machine down to a crawl until the process is finished.
- After updating both the engine and behavior, I boot the game up and greeted with PC and NPCs is always in idle animation floating around the town. The jumping, unsheathing weapon is not working, rendering the game unplayable.

CGO from the look of it is quite a fun mod and I really want to try it out but these issues are preventing me from enjoying it. Please look into it as soon as you can.

**Comment by ShikyoKira** [comment] 2020-03-31 16:22
Duplicate of #168 
please have your issues separate in few issues not all in 1
CPU hit 100% utilization is not an issue per say but inefficiency none the less, it has been tuned in the devs version anyway so u should have better performance when using the next version

**Closed** 2020-03-31 16:22 UTC

**Comment by tridbee** [comment] 2020-03-31 23:34
> Duplicate of #168
I don't think that's the same issue I described. The issue I want to get across is how both the player and NPCs always stuck in the idle animation pose and cannot jump at all. They can still move around along the ground but that's it, no other action can be done within the game.
