### ISSUE TITLE
Game crash on launch/sliding idle bug if there are more than 13500 animations

### ISSUE THREAD

**Issue by woodhawk109** [ShikyoKira/Project-New-Reign---Nemesis-Main#221] opened 2020-04-20 23:44 UTC
Hi Shiro,

Just letting you know that if someone has over 13500 animations after patching with Nemesis, the game will either do one of two things:

1. The game will crash immediately on launch (before the Skyrim logo even appears on the menu). By reducing the animation count to below 13500 by deleting one of the added animation folder, the game can launch and everything seems to work fine but go over that and it crashes on launch. When used with Crashfix, the crash fix mod will say that the game ran out of system memory when  trying to launch

2. In some rare cases, even with 20,000+ animations, the game can sometimes launch and I can even load a save just fine, but the characters will be sliding around with no walking animations. It's not a T-pose as the idle animation can play, just cannot draw your weapons or attack or do anything except sliding around. This applies to NPCs and creatures as well

Please see the patch log below. After patching, my game crashes on launch. But by removing one of the SLAL's animation folder and reducing the anim counts to around 13200, I can play the game fine

Hopefully this can help you figure out a way to fix this. Thanks for you hard works

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4506835/PatchLog.txt)

**Comment by ShikyoKira** [comment] 2020-04-21 14:42
Duplicate of #178 
you can rest assure regarding a fix for this. It has been addressed and fixed in devs build

**Closed by ShikyoKira** 2020-04-21 14:42 UTC
