### ISSUE TITLE
Error (6002) Exception has occured

### ISSUE THREAD

**Issue by HarperZ9** [ShikyoKira/Project-New-Reign---Nemesis-Main#235] opened 2020-04-29 17:13 UTC
ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: C:\Users\zaind\AppData\Local\Nemesis\Nemesis_AA_Core.pex
Message: boost::filesystem::remove: The process cannot access the file because it is being used by another process: "C:\Users\zaind\AppData\Local\Nemesis\Nemesis_AA_Core.pex"

mentioned to report to author immediately, so I went ahead and wanted to post this to you

**Comment by jadeonking** [comment] 2020-04-30 02:58
I also ran into this issue i'm running it through Mod Organizer 2 if that helps any

**Comment by ShikyoKira** [comment] 2020-04-30 17:04
Duplicate of #195

**Closed by ShikyoKira** 2020-04-30 17:04 UTC

**Comment by OkanSen** [comment] 2020-05-04 13:58
Hi, sorry for reopening the thread, but I didn't want to create a new thread for it. I'm having the same error code. Upon downloading and setting it up the first time it worked just fine. It generated 6400ish animations. Then I rerun it again to make sure of some file changes, then it's constantly giving this error. And it is not the duplicate of #195, output is as follows;

ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: None
Message: boost::filesystem::remove: The process cannot access the file because it is being used by another process: "temp_behaviors\xml\_1stperson\magicbehavior.xml"

Failed to generate behavior

Even if it is the same reason for #195, I've done what you have stated in that thread "re run the operation", but it always gives the same error.
