### ISSUE TITLE
Error 1025

### ISSUE THREAD

**Issue by AgonizingPain** [ShikyoKira/Project-New-Reign---Nemesis-Main#149] opened 2020-02-11 13:01 UTC
I am new to this and I don't know what to do here's the error

ERROR(1025): Failed to output xml file
File: temp_behaviors\xml\1hm_locomotion

**Comment by ShikyoKira** [comment] 2020-02-11 13:02
Rerun it again

**Comment by AgonizingPain** [comment] 2020-02-11 13:11
It happens all the time

**Comment by AgonizingPain** [comment] 2020-02-11 13:47
I tried this out just now and I haven't got it working yet

**Comment by AgonizingPain** [comment] 2020-02-11 16:20
ERROR(1025): Failed to output xml file
File: temp_behaviors\xml\attackbehavior

Failed to generate behavior

**Comment by ShikyoKira** [comment] 2020-02-13 17:03
make sure you run the tool with admin privilege. and... this happen when you are trying to update the engine right?

**Comment by AgonizingPain** [comment] 2020-02-17 12:51
I run MO2 with admin privilege and  I have noticed it works if i dont use ita as an executable in MO2 but then it dosent detect any of my mods. It used to happen when i launched the engine but now when i try to update the engine I get this

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: boost::filesystem::create_directory: The system cannot find the path specified: "temp_behaviors\_1stperson\"

**Comment by ShikyoKira** [comment] 2020-02-21 17:04
how about you install it manually and then execute it through MO2 as usual?

**Comment by ShikyoKira** [comment] 2020-04-15 07:37
Duplicate of #195

**Closed by ShikyoKira** 2020-04-15 07:37 UTC
