### ISSUE TITLE
Nemesis animation cap

### ISSUE THREAD

**Issue by HaloGalaxy25** [ShikyoKira/Project-New-Reign---Nemesis-Main#210] opened 2020-04-15 03:17 UTC
So I've recently moved to Nemesis from FNIS and I did uninstall FNIS completely but the game crashes ON the bethesda logo every time I launch it, I found out it was due to the large number of animations, my animations registered is currently at 17k the game loads fine below 15k I have seen people play with over 20k animation count so I hope theirs a fix for this or else I might have to go with the nuclear option and uninstall the game completely and then reinstall it.

**Comment by Assad76** [comment] 2020-04-15 03:41
Same here.

**Comment by ShikyoKira** [comment] 2020-04-15 05:14
don't reinstall the game. once above 15k you can try your luck. There are certain animations you can go beyond that. Anyway, i'll close this as this is a duplication

Duplicate of #178

**Closed by ShikyoKira** 2020-04-15 05:14 UTC
