### ISSUE TITLE
Nemesis Engine Update

### ISSUE THREAD

**Issue by ArcanePoro** [ShikyoKira/Project-New-Reign---Nemesis-Main#143] opened 2020-02-06 10:02 UTC
When attempting to run the Nemesis engine update for Skyrim SE with the v0.83c-beta version, this error occurs.

ERROR(6001): An exception has occurred while updating. Report to Nemesis' author immediately
Message: boost::filesystem::create_directory: The system cannot find the path specified: "temp_behaviors\_1stperson\"

Looking at the specified folder "temp_behaviors" there is only an "xml" folder that has a "_1stperson" folder within it. Attempting to create an empty "_1stperson" folder inside "temp_behaviors" and then running the update again deletes the "_1stperson" folder.

**Comment by ShikyoKira** [comment] 2020-02-06 14:32
post your updatelog.txt

**Comment by ArcanePoro** [comment] 2020-02-06 18:19
I went back to get the log again and it worked for some reason now. Did nothing to it and now it works 8 hours later. If it pops up again I will come back, but for now I will just close this thread.

**Comment by ArcanePoro** [comment] 2020-02-06 18:48
Attempting to update now works for unknown reasons, did not touch the program or associated files within the time period. However, a new error has occurred during patching. 

Initializing behavior generation

Mod Checked 1: nemesis
Mod Checked 2: agpo
Mod Checked 3: cbbi
Mod Checked 4: rthf
Mod Checked 5: tkuc
Mod Checked 6: zcbe

Mod installed: FNISBase
Mod installed: ImmersiveAnimatedLooting
Mod installed: JZBai_ThrowingWpnsLite
Mod installed: NAR
Mod installed: SSM
Mod installed: TSC
Mod installed: XPMSE

ERROR(6002): An exception has occured while patching. Report to Nemesis' author immediately
File: temp_behaviors\xml\_1stperson\
Message: boost::filesystem::create_directory: The system cannot find the path specified: "temp_behaviors\xml\_1stperson"

Failed to generate behavior

**Comment by ShikyoKira** [comment] 2020-04-15 05:18
Duplicate of #195

**Closed by ShikyoKira** 2020-04-15 05:18 UTC

**Comment by mitsoswu** [comment] 2023-10-24 04:13
Check this out:  

https://www.reddit.com/r/skyrimmods/comments/pgvwz9/psa_for_those_of_you_getting_nemesis_unlimited/
