### ISSUE TITLE
ERROR(1025): Failed to output xml file File: temp_behaviors\xml\1hm_locomotion

### ISSUE THREAD

**Issue by Morpheonix** [ShikyoKira/Project-New-Reign---Nemesis-Main#223] opened 2020-04-21 07:33 UTC
This is the error I receive everytime i click launch.  I checked out the folder titled "xml" that's in the error message and it is empty. Is there supposed to be files in it? Totally lost here.

**Comment by ShikyoKira** [comment] 2020-04-21 14:39
Duplicate of #173 both errors are same. The code different is easier for me to locate the issue location

**Closed by ShikyoKira** 2020-04-21 14:39 UTC
