### ISSUE TITLE
Nemesis Stuck

### ISSUE THREAD

**Issue by Hawke-Esq** [ShikyoKira/Project-New-Reign---Nemesis-Main#201] opened 2020-04-12 14:35 UTC
My Mods: https://modwat.ch/u/Hawke/plugins

Nemesis is stuck like this; https://i.imgur.com/eqdiWuj.png for the last hour, is it supposed to take this long?

**Comment by ShikyoKira** [comment] 2020-04-13 10:55
Duplicate of #148

**Closed by ShikyoKira** 2020-04-13 10:55 UTC

**Comment by Hawke-Esq** [comment] 2020-04-13 14:50
@ShikyoKira I fixed it by changing language to English from Turkish, I think the issue comes from the letter "i". In Turkish we have 2 different letters as "I , ı" and "İ , i" but in English they are same "I , i". Dunno how programming works but I think issue lies here.
