### ISSUE TITLE
Update Engine runs faster when minimized.

### ISSUE THREAD

**Issue by andrelo1** [ShikyoKira/Project-New-Reign---Nemesis-Main#102] opened 2019-06-06 19:39 UTC
Update Engine process takes significantly longer time when window is on top, it takes 430 seconds. But if I send window to back or minimize it takes 22 seconds.
Also when window is on top it cause high cpu load and cause other applocations to stuck.

**Comment by ShikyoKira** [comment] 2019-06-08 14:03
It sometimes takes very long, usually very fast. It seems to be quite random and doesn't seem to have anything to do with minimizing the window. Its a known problem. Still I'll leave this open so that i can come back to it in future

**Comment by andrelo1** [comment] 2019-06-09 09:15
> It seems to be quite random and doesn't seem to have anything to do with minimizing the window.

May be, but on my side it is 100% reproducible. And it only affect "Update Engine", but not "Launch Engine". I can suppose that it could be related to UI.

**Comment by ShikyoKira** [comment] 2019-06-22 15:16
wanna clarify this again. Is it that it stuck at 99% for a long time?

**Comment by andrelo1** [comment] 2019-07-02 10:34
No, it stuck at around 54%.

**Comment by ShikyoKira** [comment] 2019-07-02 15:51
Ok. Its really hard to pinpoint where it is getting stuck at. Let's discuss this further on discord if you have an account. Drop me a msg there. Shiki - ShikyoKira#3754

**Comment by ShikyoKira** [comment] 2019-08-09 19:55
I have made changes to the multithreading structure, which i suspect is the cause. Please look into it and see if it has been fixed in the latest version

**Comment by andrelo1** [comment] 2019-10-18 13:30
I installed 0.82d-beta and issue is not gone. Update process goes much slower when window is on top.

**Comment by ShikyoKira** [comment] 2019-12-09 21:00
Multithreading structure has been restructured. This problem has been minimized but may still occur to lower end CPU

**Closed by ShikyoKira** 2019-12-09 21:00 UTC
