### ISSUE TITLE
Update engine error

### ISSUE THREAD

**Issue by masterrite** [ShikyoKira/Project-New-Reign---Nemesis-Main#324] opened 2020-07-11 01:32 UTC
I```
nitializing engine update

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: No mapping for the Unicode character exists in the target multi-byte code page.

Failed to update engine
```

**Comment by ShikyoKira** [comment] 2020-07-11 04:57
![image](https://user-images.githubusercontent.com/31563634/87216817-c14f2180-c375-11ea-985b-05d1faff0f1b.png)

This issue fails to meet all the criteria in the description in the [main page](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main) of this repo
Duplicate of #273

**Closed by ShikyoKira** 2020-07-11 04:57 UTC
