### ISSUE TITLE
Everyone T Posing

### ISSUE THREAD

**Issue by RaccKing21** [ShikyoKira/Project-New-Reign---Nemesis-Main#254] opened 2020-05-12 14:10 UTC
I followed this tutorial: https://youtu.be/4lSp3tZI2xc
Installed CGO and everything according to instructions.
Disabled animation replacers just in case.

Warning Check says: animation has not been registered in _1stperson\firstperson.hkx file. The animation will not work. Please contact mod author.

All animations worked perfectly with FNIS
Please help

**Comment by ShikyoKira** [comment] 2020-05-13 05:14
Duplicate of #220

**Closed by ShikyoKira** 2020-05-13 05:14 UTC
