### ISSUE TITLE
Sexy Aroused Idles SSE conflicting with Devious Devices

### ISSUE THREAD

**Issue by Bonsaiyeen** [ShikyoKira/Project-New-Reign---Nemesis-Main#249] opened 2020-05-08 04:11 UTC
Installing these two mods and loading them together in nemesis causes devious devices to play its aroused animations in place of the idles mod. 

Modlink:
https://www.loverslab.com/files/file/8622-aroused-sexy-idles-animations-sse-conversion/

**Comment by ShikyoKira** [comment] 2020-05-08 06:11
Duplicate of #134 

regardless of the mod, both this issue and #134 are the result of the same mechanics so i'll lump all from the same faulty mechanics together

**Closed by ShikyoKira** 2020-05-08 06:11 UTC
