### ISSUE TITLE
Error 6001 when updating engine

### ISSUE THREAD

**Issue by Yuheeeng** [ShikyoKira/Project-New-Reign---Nemesis-Main#319] opened 2020-07-06 10:02 UTC
[CriticalLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878144/CriticalLog.txt)
[UpdateLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4878145/UpdateLog.txt)
<img width="273" alt="How it looks like" src="https://user-images.githubusercontent.com/49990364/86581502-73ef4080-bf80-11ea-8568-f865a9597d51.png">

Btw the error message translates into: 
In the multibyte target code page, there is no character to which this Unicode character can be mapped.

**Comment by ShikyoKira** [comment] 2020-07-06 15:45
Duplicate of #273

**Closed by ShikyoKira** 2020-07-06 15:45 UTC
