### ISSUE TITLE
nem se crashes when click: update engine

### ISSUE THREAD

**Issue by dmm233** [ShikyoKira/Project-New-Reign---Nemesis-Main#321] opened 2020-07-09 08:10 UTC
nem se crashes when click: update engine
logs below:
Initializing engine update

ERROR(6001): An exception has occured while updating. Report to Nemesis' author immediately
Message: �ڶ��ֽڵ�Ŀ������ҳ�У�û�д� Unicode �ַ�����ӳ�䵽���ַ���

Failed to update engine

**Comment by ShikyoKira** [comment] 2020-07-11 04:48
Please stop sending duplicate report. Take you time and look at some active issues and see if there is any open issue mentioning this issue. If there is, then don't. Don't be lazy, there are only about 40 active issues here. This issue clearly isn't meeting the criteria stated in description in the main page of this repo

Duplicate of #273

**Closed by ShikyoKira** 2020-07-11 04:48 UTC
