### ISSUE TITLE
TUDM animation broken

### ISSUE THREAD

**Issue by sreejith1234kris2** [ShikyoKira/Project-New-Reign---Nemesis-Main#187] opened 2020-03-28 16:01 UTC
Using nemesis with TUDM broke dodge and power attack animations in third person, animation applied in same spot without moving

**Comment by xFrosty7** [comment] 2020-03-28 16:43
it's not just tudm, cgo & tk dodge (with patches) also have the same issue with nemesis. :/

**Comment by sreejith1234kris2** [comment] 2020-03-28 17:09
Any fix

**Comment by xFrosty7** [comment] 2020-03-29 08:04
nope, still looking for a way to fix this

**Comment by keny25** [comment] 2020-03-29 14:39
I had the same problem, marking the boxes [combat behavior enhanced, retime hit frame, ultimate combat/tk dodge, the ultimate dodge mod and turning animation won't affect upper body] fixed this problem

**Comment by ShikyoKira** [comment] 2020-03-30 05:25
Duplicate of #157

**Closed** 2020-03-31 16:23 UTC

**Comment by Simonuell** [comment] 2020-04-08 21:10
GUYS I found A SOLUTION.
1. Install all your animation mods
2.Run Nemesis as usual, click on CGO patch, etc
3.Install your CGO once again and let it overwrite animationdatasinglefile.txt, which is 1.8 mb or so
(MO users like me might wanna do that in OVERWRITE folder, can you believe, install CGO there and g0!)
4. FOR those who have DODGE animation broken, might have not noticed that sprinted power attack IS STUCK like dodge too. IT FIXES EVEN THAT
