### ISSUE TITLE
5822 Warnings (1013) on Fresh, Pure Vanilla SSE Install (nothing else installed at all)

### ISSUE THREAD

**Issue by Spawnblade** [ShikyoKira/Project-New-Reign---Nemesis-Main#253] opened 2020-05-10 13:17 UTC
As noted in title.  My previous Skyrim install was throwing the same warnings, so I wanted to see what the difference would be on a fresh install -- and there was none.  I even tried running it from the base SSE directory instead of through Mod Organizer to see if it was the cause... But there was no change.  If you need specifics, I can get them, but unfortunately the file is far too large for pastebin.  This can't be what's supposed to happen, yeah?

[edit]  Nevermind, I see that I am not alone with this issue.  Worth noting that -- at least from some testing -- things seem functional at present with a baseline install.  Need to do more experimenting to see if I get any T-poses or freezing. [/edit]

**Comment by ShikyoKira** [comment] 2020-05-18 14:37
thanks for reporting. The warning does not mean your skyrim is broken or anything, just informing the users something is out of ordinary. So long it is working and running fine, you can ignore them. I'll give this a look if I have time

**Comment by ShikyoKira** [comment] 2020-05-26 20:47
Duplicate of #222

**Closed by ShikyoKira** 2020-05-26 20:47 UTC
