### ISSUE TITLE
Error when generating behavior

### ISSUE THREAD

**Issue by Theandrin** [ShikyoKira/Project-New-Reign---Nemesis-Main#264] opened 2020-05-23 08:50 UTC
Hello can someone please help me with the installation?
I have an issue when trying to use Nemesis for installing CGO for Skyrim.
I installed Nemesis (the newest from 11 Jan), added the Nemesis.exe from Engine (using MO2), installed CGO SE, launched Nemesis, updated engine, ticked the CGO and then pressed Launch Behavior Engine and I'm getting this error message below:

ERROR(5001): Invalid format has been detected in "animationsetdatasinglefile.txt". Please contact the template creator or mod author
Project: DefaultFemaleData\DefaultFemale.txt
Header: DragonMountedMRhSolo_ShieldOrTorch.txt

Failed to generate behavior

Does anyone have any ideas about what I should do, please?

Thanks

**Comment by ShikyoKira** [comment] 2020-05-26 11:48
Please provide more info. Test and research. Nemesis has more than 300 error messages, Error message has designed to deal with issue not on my side but user's side. So please test it in a clean load order to see if same issue is there or else test more

**Comment by ShikyoKira** [comment] 2020-05-26 18:43
Duplicate of #155 
Check this issue out

**Closed by ShikyoKira** 2020-05-26 18:43 UTC

**Comment by LordKioster** [comment] 2020-06-03 21:10
I have a super rare problem where animations work well no problem but only with female characters... for male characters when I use the Dodge loads the animation but does not move stays still in place
