### ISSUE TITLE
WARNING(1013). No animations except the idle animations is playing when I move. 

### ISSUE THREAD

**Issue by Reiei8** [ShikyoKira/Project-New-Reign---Nemesis-Main#204] opened 2020-04-13 11:38 UTC
I installed 360 Movement, Nemesis, and CGO according to the tutorial YT vid but when I get into the game, my character is in his idle animation in any of his movements. I can't attack, sheath/unsheath my weapons/spells, I can't jump, only run around but there's only his idle animation. So, I tried to relaunch Nemesis again and check the 'Warning Checks' and I got errors (1003) and (1013) 

[PatchLog.txt](https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/files/4469335/PatchLog.txt)

Here's my patch log.

**Comment by ShikyoKira** [comment] 2020-04-13 21:37
Reduce the number of animations count to roughly 10k. This bug occurs when it goes beyond that number too far. This is a bug not nemesis limitation

**Comment by ShikyoKira** [comment] 2020-04-14 05:29
Might be possible duplication of #142

**Comment by Reiei8** [comment] 2020-04-14 06:08
> Reduce the number of animations count to roughly 10k. This bug occurs when it goes beyond that number too far. This is a bug not nemesis limitation

Is this a user error type of bug or a bug on Nemesis itself? Kinda dissapointing it could only load 10k below. I removed some mods and it started working fine again.

**Comment by ShikyoKira** [comment] 2020-04-14 18:40
this is why it is still in beta. There is a quick fix for user as this is template issue not engine issue, modifying the txt file should be able to fix it. But best leave the fix to me

**Comment by ShikyoKira** [comment] 2020-04-14 18:40
Duplicate of #142

**Closed by ShikyoKira** 2020-04-14 18:40 UTC
