### ISSUE TITLE
Animated Armoury LE error

### ISSUE THREAD

**Issue by zodiac213** [ShikyoKira/Project-New-Reign---Nemesis-Main#124] opened 2020-01-04 08:41 UTC
Using the latest version of nemesis and trying to patch AA and these error messages pop up in the log.

WARNING(1027): 64bit hkx file detected. This file is not supported by current skyrim's architecture
File: C:\Program Files (x86)\Steam\steamapps\common\Skyrim\Data\meshes\actors\character\animations\NAR\NAR0_2hm_blockhitB .hkx

Didn't see any posts on the AA page about this,so I'm just letting both parties know what's happening.

**Comment by ShikyoKira** [comment] 2020-01-04 17:54
First of all, warning is not error. We likely won't fix warning because it is something caused by either the mod or user themselves

I believe the message is correct you inform AA's author about it. I'll close this issue as it is something we can't fix. I'll re-open this issue if this is a false positive. Thanks for reporting

**Closed by ShikyoKira** 2020-01-04 17:54 UTC
